version: "2"
run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - cyclop
    - asciicheck
    - unparam
    - unconvert
    - bodyclose
    - nilerr
    - wastedassign
    - usestdlibvars
    - testifylint
    - perfsprint
    - gosec
    - errorlint
  settings:
    gosec:
      includes:
        - G102
        - G106
        - G108
        - G109
        - G111
        - G112
        - G201
        - G203
    perfsprint:
      int-conversion: true
      err-error: true
      errorf: true
      sprintf1: true
      strconcat: true
    testifylint:
      enable-all: true

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofmt:
      rewrite-rules:
        - pattern: "interface{}"
          replacement: "any"
