app:
  env: "dev"
  addr: "127.0.0.1"
  port: "8080"
log:
  level: "info" # debug, info, warn, error
  format: "console" # "json" або "console"
mongo:
  uri: "mongodb://root:secret@localhost:27017"
  db: "pollparlor"
